### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by AJSagan** [El-Qassam/JavaScript-Caclulator#3]
So this is Github? Looks like a nerd hangout. Like your friend group. Your account looks pretty fancy. Chatting through a message system for reporting issues is pretty low key as well, but I guess it works for school?

Also, are you going to the United camp? I just got the form signed. Try to get it in so hopefully we can have nearby rooms.

**Comment by AJSagan** [comment]
Answer. You said you’d be here at 5.

**Comment by El-Qassam** [comment]
> So this is Github? Looks like a nerd hangout. Like your friend group. Your account looks pretty fancy. Chatting through a message system for reporting issues is pretty low key as well, but I guess it works for school?
> 
> Also, are you going to the United camp? I just got the form signed. Try to get it in so hopefully we can have nearby rooms.

Okay. GitHub is a place for smart people. Girl I know for a fact you ain’t making fun of the bois. I don’t even wanna talk about your friend group. A bunch of Karen’s whose only purpose is to hold up the line at Kroger just to call the manager over a 14 instead of 15 piece pack of gum.

ANYways, I got the form signed, should be good to go on Saturday. We should definitely get nearby rooms. What number did you draw?

**Comment by El-Qassam** [comment]
> Answer. You said you’d be here at 5, tsk tsk.

Are _you_ still here?

**Comment by AJSagan** [comment]
Well its about time.

**Comment by AJSagan** [comment]
Well, at least my friends don’t sound like 7 year olds. Your words, not mine. I got 512. Try to get like 513 or something. Pretend you don’t care. Maybe you could trade?

**Comment by AJSagan** [comment]
Still here, are you though? I was just exploring the depths of your account. Some weird nerd stuff going on. Who’s the “Mr. Waltz” person that keeps dissing you?

**Comment by AJSagan** [comment]
What are you doing for this long?

**Comment by El-Qassam** [comment]
Girl calm down. I can see you’re typing essays, just waiting for you to get done. I’m also trying to finish my work because of the field trip.

**Comment by El-Qassam** [comment]
> Well, at least my friends don’t sound like 7 year olds. Your words, not mine. I got 512. Try to get like 513 or something. Pretend you don’t care. Maybe you could trade?

Let’s goooo. I got 515. Good enough? I might try to ask the guys if anyone got 513 or 511.

**Comment by El-Qassam** [comment]
> Well, at least my friends don’t sound like 7 year olds. Your words, not mine.

They’re like innocent 7 year olds. Scratch that. Maybe not innocent, but certainly childish. They’re nice, its not like they mean the damage they cause to society.

**Comment by AJSagan** [comment]
> > Well, at least my friends don’t sound like 7 year olds. Your words, not mine. I got 512. Try to get like 513 or something. Pretend you don’t care. Maybe you could trade?
> 
> Let’s goooo. I got 515. Good enough? I might try to ask the guys if anyone got 513 or 511.

Nice. That sounds awesome. We’ll definitely have a blast if we get close rooms. Chloe might ruin it though.

**Comment by AJSagan** [comment]
But you didn’t tell me who “Mr. Waltz” is?

**Comment by El-Qassam** [comment]
> But you didn’t tell me who “Mr. Waltz” is?

He’s Braylen. A close friend of mine. I think you might’ve seen me with him before? Guy with dreads.

**Comment by AJSagan** [comment]
I think I saw someone with dreads at your lunch table.

**Comment by AJSagan** [comment]
Speaking of lunch, when can we sit together again?

**Comment by El-Qassam** [comment]
> > > Well, at least my friends don’t sound like 7 year olds. Your words, not mine. I got 512. Try to get like 513 or something. Pretend you don’t care. Maybe you could trade?
> > 
> > 
> > Let’s goooo. I got 515. Good enough? I might try to ask the guys if anyone got 513 or 511.
> 
> Nice. That sounds awesome. We’ll definitely have a blast if we get close rooms. Chloe might ruin it though.

I know. Honestly can’t wait. Some peaceful quiet time. I know how to deal with Chloe. Just throw a bag of Hershey kisses outside and out she goes.

**Comment by El-Qassam** [comment]
> I think I saw someone with dreads at your lunch table.

That’s him. He’s really nice.

**Comment by AJSagan** [comment]
> > I think I saw someone with dreads at your lunch table.
> 
> That’s him. He’s really nice.

Ok. Is he weird like how you describe the rest of them? What would he think of us?

**Comment by El-Qassam** [comment]
> Ok. Is he weird like how you describe the rest of them? What would he think of us?

No, he’s perhaps the only serious guy in the roster. Uhh… from the culture differences type of aspect, not much I think? He’s not racist.

**Comment by El-Qassam** [comment]
> Speaking of lunch, when can we sit together again?

I dunno, honestly. I don’t wanna leave the bois alone for too long. A) They already have a vague idea about us. B) I just like them too much.

We can always meet after practice? We’ve got our time.

**Comment by AJSagan** [comment]
> > Ok. Is he weird like how you describe the rest of them? What would he think of us?
> 
> No, he’s perhaps the only serious guy in the roster. Uhh… from the culture differences type of aspect, not much I think? He’s not racist.

Ok. That’s an improvement from the hypotheticals you told me about the rest of them, lol. Definitely the Ethan dude…

**Comment by El-Qassam** [comment]
> Ok. That’s an improvement from the hypotheticals you told me about the rest of them, lol. Definitely the Ethan dude… and the Hassan guy. I guess you’re right. Half the people at our school are so weird that the thought of anyone talking turns dark very very quickly. Remember what I told you the Locklan dude said?

True. Ethan just needs help in general. Hassan would just disapprove because he’s Muslim as well? Like if someone at school has an idea about you that’s bad, then that’s an issue. But if it’s a brother, then that’s a whole other story. The priest gonna slide on the opps, the entire community makes fun of “so-and-so’s son”, and you aren’t generally the most popular kid on Earth.

You’re so right. Lochlan (where tf did you get Locklan) is pretty devious… I vividly remember his comments.

**Comment by AJSagan** [comment]
LOL. Yeah, I get that. Our rabbi wouldn’t care too much because he’s gay, but yeah.

**Comment by AJSagan** [comment]
Imagine still working on your school work though…

**Comment by El-Qassam** [comment]
> LOL. Yeah, I get that. Our rabbi wouldn’t care too much because he’s gay, but yeah.

Consider yourself lucky. Wait, is that the guy in your one sacrament video? I should start bullying you about that again. Girl thought she could dox me 😎.

**Comment by El-Qassam** [comment]
> Imagine still working on your school work though…

Shut up. Girl’s literally in Algebra 2. Nothing is hard for you. Minus history of course? Tanzania is in Europe? Remember???

**Comment by AJSagan** [comment]
The bat mitzvah? Dude, if you play that one more time, I will slide ice down your jersey. I can tell you liked it from yesterday.

**Comment by AJSagan** [comment]
Don’t talk. You were literally reading a textbook during your free time. You were Mr. Mazock’s epic teacher’s pet. He was practically your dad.

**Comment by El-Qassam** [comment]
> Don’t talk. You were literally reading a textbook during your free time. You were Mr. Mazock’s epic teacher’s pet. He was practically your dad.

I wasn’t reading it, I was looking if it mentioned the US’ sometimes embarrassing actions. Okay. He wasn’t my dad. We were just good friends.

**Comment by El-Qassam** [comment]
Girl, you’re everywhere because of that thing. Better delete it. Too bad I downloaded it though 😎 .

**Comment by AJSagan** [comment]
You did not just put that on a public chat.

**Comment by AJSagan** [comment]
Sometimes I dislike you so strongly. I will get even.

**Comment by AJSagan** [comment]
I wanted to delete it, but my parents don’t want to. Why did 127 random people watch this?

**Comment by El-Qassam** [comment]
> You did not just put that on a public chat.

Oh yes I did.

**Comment by El-Qassam** [comment]
> I wanted to delete it, but my parents don’t want to. Why did 127 random people watch this?

Me all 127 times, baby.

**Comment by El-Qassam** [comment]
> Sometimes I dislike you so strongly. I will get even.

I’d like to see you try.

**Comment by AJSagan** [comment]
Oh you better believe I will, Malek whatever your middle name is Kamal.

**Comment by El-Qassam** [comment]
I’d like to see you try, Ashlyn Julia Sagan. Always one step ahead, 😎.

**Comment by El-Qassam** [comment]
Also, Braylen was the one I was telling you about who kept saying your name is weird. He has a point though. Who naturally names their child Ashlyn?

**Comment by AJSagan** [comment]
You’re literally no fun.

**Comment by AJSagan** [comment]
Tell him who names their child Malek?

**Comment by El-Qassam** [comment]
A lot of people.

**Comment by El-Qassam** [comment]
WAIT. Yoooo. Tyler Pape told me he got 513. He says he want’s 515 because Zach’s at 514. We got a deal.

**Comment by AJSagan** [comment]
YES. It’s gonna be so fun. We’re gonna dust the huntington kids, then we’re gonna get like the whole day off. Gonna enjoy that sunshine.

**Comment by El-Qassam** [comment]
We just got like 2 good days together back to back. Prep field trip and then camp.

**Comment by AJSagan** [comment]
Yes. The field trip was okay with you, but omg the credit card part was so annoying.

**Comment by El-Qassam** [comment]
It was actually really easy. The kids were just so genius they couldn’t scan a card. Anyways, I gtg finish my work.

**Comment by El-Qassam** [comment]
The trip was pretty good though.

**Comment by El-Qassam** [comment]
Also, never use “omg” in my presence again. It makes you sound like the Karen you are not.

**Comment by AJSagan** [comment]
Lol, fine.

**Comment by AJSagan** [comment]
Cya. Have “fun” with your work.

**Comment by El-Qassam** [comment]
I did. Just got done.

**Comment by El-Qassam** [comment]
I am. I was just with the bois.

**Comment by El-Qassam** [comment]
> So why do we need to use this? The document thing works just as fine.

It’s just better.

**Comment by AJSagan** [comment]
What are you guys doing right now?

**Comment by El-Qassam** [comment]
We’re watching a weird movie about hockey.

**Comment by AJSagan** [comment]
Same.

**Comment by El-Qassam** [comment]
Sure. Have fun with your Karen friends.

**Comment by El-Qassam** [comment]
Get on the phone. Or here.

**Comment by El-Qassam** [comment]
I’m getting tired of the boys’ antics. We should schedule a lunch together sometime. Also, I won’t bet at practice on Thursday, appointment.

**Comment by AJSagan** [comment]
I don’t know. I thought we agreed that after practice was enough? I guess we can if you want to. Also, I texted you the camp schedule.

**Comment by El-Qassam** [comment]
I guess you’re right. I just get tired of their weird selves really quickly. The schedule looks good, nothing major from the old one.

**Comment by AJSagan** [comment]
Ok. Good. Could you come over during tech?
